name: golangci-lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.3"
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --out-format=colored-line-number
